# Site settings
name: Revanth's Blog
pagetitle: Revanth Revoori
title: Sai Revanth Revoori
email: revanth001reva@gmail.com
description: Where I write about awesome things that intrigue me
baseurl: "" # the subpath of your site, e.g. /blog/
url: "rrevanth.github.io" # the base hostname & protocol for your site
author: "Revanth Revoori"

twitter_username: revanth001reva
github_username:  rrevanth
instagram_username: revanth001reva
dribbble_username: revanth001reva
linkedin_username: revanthrevoori

# Build settings
markdown: kramdown
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md']

# paginate: 2
# paginate_path: "/page:num/"

kramdown:
  input: GFM
  syntax_highlighter: rouge

gems:
- jemoji
- jekyll-mentions
- jekyll-redirect-from
- jekyll-sitemap
- jekyll-feed
