# Site settings
pagetitle: Sai Revanth Revoori
title: Revanth Revoori
email: revanth001reva@gmail.com
description: I am a developer, photography enthusiast, and self-proclaimed music connoisseur.This is where I write about awesome things that intrigue me.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://rrevanth.github.io" # the base hostname & protocol for your site

twitter_username: revanth001reva
github_username:  rrevanth
instagram_username: revanth001reva
dribbble_username: revanth001reva
linkedin_username: revanthrevoori

permalink: /:categories/:title

# Build settings
markdown: kramdown
exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml

# paginate: 2
# paginate_path: "/page:num/"

kramdown:
  input: GFM
  syntax_highlighter: rouge

name: Revanth's Blog
author: "Revanth Revoori"

gems:
- jemoji
- jekyll-mentions
- jekyll-redirect-from
- jekyll-sitemap
- jekyll-feed
