---
title: Revanth Revoori
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
pagetitle: Revanth Revoori
email: revanth001reva@gmail.com
description: I am a developer, photography enthusiast, and self-proclaimed music connoisseur.This
  is where I write about awesome things that intrigue me.
baseurl: ''
url: http://rrevanth.github.io
twitter_username: revanth001reva
github_username: rrevanth
instagram_username: revanth001reva
dribbble_username: revanth001reva
linkedin_username: revanthrevoori
markdown: kramdown
exclude:
- README.md
- Rakefile
- Gemfile
- ".deploy_key.enc"
- publish.bat
- travis
- Gemfile.lock
- changelog.md
- "*.Rmd"
- vendor
- ".travis.yml"
permalink: "/:categories/:year/:month/:title"
escape_code: true
encoding: utf-8
sass:
  style: compressed
excerpt_separator: "<!--more-->"
kramdown:
  input: GFM
  syntax_highlighter: rouge
name: Revanth's Blog
author: Revanth Revoori
lunr_search:
  excludes:
  - rss.xml
  - atom.xml
  stopwords: stopwords.txt
  min_length: 2
gems:
- jemoji
- jekyll-redirect-from
- jekyll-sitemap
- jekyll-feed
prose:
  siteurl: http://rrevanth.github.io/
  relativeLinks: http://rrevanth.github.io/links.jsonp
  media: assests/media
  metadata:
    _posts/blog:
    - name: layout
      field:
        element: hidden
        value: blogpost
    - name: title
      field:
        element: text
        label: Enter title of the Article
        placeholder: Enter Title
    - name: date
      field:
        element: text
        label: Date
        value: CURRENT_DATETIME
    - name: author
      field:
        element: hidden
        value: Revanth Revoori
    - name: published
      field:
        element: hidden
        value: 'true'
    - name: category
      field:
        element: hidden
        value: blog
        alterable: 'true'
    - name: categories
      field:
        element: hidden
        value: blog
        alterable: 'true'
    - name: tags
      field:
        element: multiselect
        label: Add Tags
        placeholder: Add Tags
        options:
        - name: Blog
          value: blog
        alterable: true
    - name: excerpt_separator
      field:
        element: text
        value: "<!--more-->"
    _posts/reads:
    - name: layout
      field:
        element: hidden
        value: readpost
    - name: title
      field:
        element: text
        label: Enter title of the Article
        placeholder: Enter Title
    - name: date
      field:
        element: text
        label: Date
        value: CURRENT_DATETIME
    - name: author
      field:
        element: hidden
        value: Revanth Revoori
    - name: published
      field:
        element: hidden
        value: 'true'
    - name: category
      field:
        element: hidden
        value: reads
        alterable: 'true'
    - name: categories
      field:
        element: hidden
        value: reads
        alterable: 'true'
    - name: tags
      field:
        element: multiselect
        label: Add Tags
        placeholder: Add Tags
        options:
        - name: Read
          value: read
        alterable: true
    - name: excerpt_separator
      field:
        element: text
        value: "<!--more-->"
    _posts/videos:
    - name: layout
      field:
        element: hidden
        value: videopost
    - name: title
      field:
        element: text
        label: Enter title of the Article
        placeholder: Enter Title
    - name: date
      field:
        element: text
        label: Date
        value: CURRENT_DATETIME
    - name: author
      field:
        element: hidden
        value: Revanth Revoori
    - name: published
      field:
        element: hidden
        value: 'true'
    - name: category
      field:
        element: hidden
        value: videos
        alterable: 'true'
    - name: categories
      field:
        element: hidden
        value: videos
        alterable: 'true'
    - name: tags
      field:
        element: multiselect
        label: Add Tags
        placeholder: Add Tags
        options:
        - name: Video
          value: video
        alterable: true
    - name: excerpt_separator
      field:
        element: text
        value: "<!--more-->"
