# Site settings
pagetitle: Revanth Revoori
title: Sai Revanth Revoori
email: revanth001reva@gmail.com
description: Revanth Revoori is a developer, photographer, and self-proclaimed music connoisseur.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://rrevanth.github.io" # the base hostname & protocol for your site

twitter_username: revanth001reva
github_username:  rrevanth
instagram_username: revanth001reva
dribbble_username: revanth001reva
linkedin_username: revanthrevoori

# Build settings
markdown: kramdown
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md']

# paginate: 2
# paginate_path: "/page:num/"

kramdown:
  input: GFM
  syntax_highlighter: rouge

gems:
- jekyll-mentions
- jekyll-redirect-from
- jekyll-sitemap
- jekyll-feed
