# Site settings
pagetitle: Sai Revanth Revoori
title: Revanth Revoori
email: revanth001reva@gmail.com
description: I am a developer, photography enthusiast, and self-proclaimed music connoisseur.This is where I write about awesome things that intrigue me.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://rrevanth.github.io" # the base hostname & protocol for your site

twitter_username: revanth001reva
github_username:  rrevanth
instagram_username: revanth001reva
dribbble_username: revanth001reva
linkedin_username: revanthrevoori

# Build settings
markdown: kramdown
exclude:
  - README.md
  - Rakefile
  - Gemfile
  - .deploy_key.enc
  - publish.bat
  - travis
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml

# paginate: 2
# paginate_path: "/page:num/"

# Specific settings
# @URL Setting
permalink: /:categories/:title
# Sass style for minimum space
sass:
    style: compressed
excerpt_separator: <!--more-->  # you can specify your own separator, of course.

kramdown:
  input: GFM
  syntax_highlighter: rouge

name: Revanth's Blog
email: revanth001reva@gmail.com
author: "Revanth Revoori"

gems:
- jemoji
- jekyll-mentions
- jekyll-redirect-from
- jekyll-sitemap
- jekyll-feed

# Prose.io Config
prose:
  siteurl: 'http://rrevanth.github.io/'
  relativeLinks: 'http://rrevanth.github.io/links.jsonp'
  media: 'assests/media'
  metadata:
    _posts/blog:
      - name: "published"
        field:
          element: "button"
          label: "Publish now"
          help: "Keep this On if you do not want to   publish the article right now"
          on: "Publish this"
          off: "Don't Publish"
      - name: "layout"
        field:
          element: "hidden"
          value: "blogpost"
      - name: "title"
        field:
          element: "text"
          label: "Enter title of the Article"
          placeholder: "Enter Title"
      - name: "date"
        field:
          element: "text"
          label: "Date"
          value: "CURRENT_DATETIME"
      - name: "author"
        field:
          element: "hidden"
          value: "Revanth Revoori"
      - name: "categories"
        field:
          element: "hidden"
          value: "blog"
          alterable: "true"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Add Tags"
          options:
            - name: "Blog"
              value: "blog"
          alterable: true
      - name: "excerpt_separator"
        field:
          element: "text"
          value: "<!--more-->"
    _posts/reads:
      - name: "published"
        field:
          element: "button"
          label: "Publish now"
          help: "Keep this On if you do not want to   publish the article right now"
          on: "Publish this"
          off: "Don't Publish"
      - name: "layout"
        field:
          element: "hidden"
          value: "readpost"
      - name: "title"
        field:
          element: "text"
          label: "Enter title of the Article"
          placeholder: "Enter Title"
      - name: "date"
        field:
          element: "text"
          label: "Date"
          value: "CURRENT_DATETIME"
      - name: "author"
        field:
          element: "hidden"
          value: "Revanth Revoori"
      - name: "categories"
        field:
          element: "hidden"
          value: "reads"
          alterable: "true"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Add Tags"
          options:
            - name: "Reads"
              value: "reads"
          alterable: true
      - name: "excerpt_separator"
        field:
          element: "text"
          value: "<!--more-->"
    _posts/videos:
      - name: "published"
        field:
          element: "button"
          label: "Publish now"
          help: "Keep this On if you do not want to   publish the article right now"
          on: "Publish this"
          off: "Don't Publish"
      - name: "layout"
        field:
          element: "hidden"
          value: "tidbitpost"
      - name: "title"
        field:
          element: "text"
          label: "Enter title of the Article"
          placeholder: "Enter Title"
      - name: "date"
        field:
          element: "text"
          label: "Date"
          value: "CURRENT_DATETIME"
      - name: "author"
        field:
          element: "hidden"
          value: "Revanth Revoori"
      - name: "categories"
        field:
          element: "hidden"
          value: "tidbit"
          alterable: "true"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Add Tags"
          options:
            - name: "Videos"
              value: "videos"
          alterable: true
      - name: "excerpt_separator"
        field:
          element: "text"
          value: "<!--more-->"